# Generated by Django 4.2.6 on 2023-12-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor',
            new_name='Doctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='Patient',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='time',
            new_name='Time',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='mobile',
            new_name='Mobile',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='specialization',
            new_name='Specialization',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Modile',
        ),
        migrations.AddField(
            model_name='patient',
            name='Mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
