# Generated by Django 4.2.6 on 2023-12-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_rename_date_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='AvailableDays',
            field=models.CharField(default=23, max_length=60),
            preserve_default=False,
        ),
    ]
